### ISSUE TITLE
Feature request: Multiple download option

### ISSUE THREAD

**Issue by JWebCoder** [alvarorichard/GoAnime#57]
Can you make it possible to select a range of episodes to download instead of downloading them one by one?

Thank you.

**Comment by alvarorichard** [comment]
Hello,

Thank you very much for your suggestion! In previous versions, this feature was available but was removed due to various issues it caused. I would like to add that Animatic V2 has this feature; it's based on GoAnime but focused on servers for use in Plex, and I can try to implement it as well.

Sincerely,
